"""Pydantic schemas for product summary agent."""

from pydantic import BaseModel, Field
from typing import List

class SearchQueries(BaseModel):
    """Schema for the list of search queries generated by the planning node."""
    queries: List[str] = Field(description="List of 3-5 specific search queries for product research.") 